version: '3'

services:
  matrix:
    image: girlbossceo/conduwuit:latest
    restart: unless-stopped
    volumes:
      - ./services/matrix/db:/var/lib/conduwuit/
    environment:
      CONDUWUIT_SERVER_NAME: "mrparker.dev"
      CONDUWUIT_DATABASE_BACKEND: "rocksdb"
      CONDUWUIT_DATABASE_PATH: "/var/lib/conduwuit"
      CONDUWUIT_ALLOW_REGISTRATION: "false"
      CONDUWUIT_ADDRESS: "0.0.0.0"
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      TUNNEL_TOKEN: "<fill in later get rekt>"