version: '3'

services:
  matrix:
    image: girlbossceo/conduwuit:latest
    volumes:
      - ./services/matrix/db:/var/lib/conduwuit/
    environment:
      CONDUWUIT_SERVER_NAME: "mrparker.dev"
      CONDUWUIT_DATABASE_BACKEND: "rocksdb"
      CONDUWUIT_DATABASE_PATH: "/var/lib/conduwuit"
      CONDUWUIT_ALLOW_REGISTRATION: "false"
  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      TUNNEL_TOKEN: "<fill in later get rekt>"